In [2]:
import pandas as pd
import seaborn
import numpy as np

lst1 = [1,2,4,5] #list
dct1 = {'one': 1, 'two':2, 'three':3} #dictionary 
tup1 = (1,2,3,4,5) #tuple
set1 = {1,2,3,4} # set
data = [[1,2],[3,4]] #a nested list (a list containing 2 lists) 
df = pd.DataFrame([[1,2],[3,4]], columns=['Col1','Col2'])
print(df)

   Col1  Col2
0     1     2
1     3     4


In [3]:
df['Col2'] #will return all values in Col2
df['Col2'][0] #will return the value at index 0 of Col2 

#Using iloc in DataFrame to access values
df.iloc[0,1] #will return the value 2
df.iloc[:,1] #will give all rows of Col2
df.iloc[:,:] #will give all rows and columns 
df.iloc[1,:] #will give all columns and second row

Col1    3
Col2    4
Name: 1, dtype: int64

In [4]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  #must import numpy for this to work 
arr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [5]:
np.linspace   #quick info about the function and its conditions

<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>

In [6]:
help(np.linspace)  #help function for numpy

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [7]:
np.linspace(10,20,5)   #first cond is num to start at, second is number to stop at, third will tell you how many numbers to have evenly spaced in the array

array([10. , 12.5, 15. , 17.5, 20. ])

In [8]:
np.linspace(10,20,4, endpoint = False)   #same thing as above just leaves the last number off

array([10. , 12.5, 15. , 17.5])

In [9]:
df1 = pd.DataFrame([[4, 9],[3,6],[7,8]], columns=['A', 'B'])
print(df)
df1['A'].apply(np.sqrt)   #show just one column

   Col1  Col2
0     1     2
1     3     4


0    2.000000
1    1.732051
2    2.645751
Name: A, dtype: float64

In [10]:
df1.apply(np.sqrt)   #show all columns

A         B
0  2.000000  3.000000
1  1.732051  2.449490
2  2.645751  2.828427

In [11]:
df1.apply(np.sum, axis = 0)   #produce the output of the sum of each column

A    14
B    23
dtype: int64

In [12]:
df1.apply(np.sum, axis = 1)   #produce the outpout of the sum of each row

0    13
1     9
2    15
dtype: int64

In [13]:
def sum_input(s):    #same thing through a user defined function, just showing how to send to a function
    return sum(s)

df1.apply(sum_input, axis=0)


A    14
B    23
dtype: int64

In [14]:
vec = np.arange(10, 20, 3)
print(vec)

[10 13 16 19]


In [15]:
vec=np.linspace(10,20,3)
print(vec)

[10. 15. 20.]


In [16]:
arr = np.arange(4, 20, 5)
print(arr)
print('-')
vec1 = np.arange(0, 12)
print(vec1)
print('-')
vec2 = vec1.reshape(4, 3)
print(vec2)
print('-')
vec = np.arange(10,20)
print(vec)
print('-')
vec3 = vec[np.arange(0,10,3)]
print(vec3)

[ 4  9 14 19]
-
[ 0  1  2  3  4  5  6  7  8  9 10 11]
-
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-
[10 11 12 13 14 15 16 17 18 19]
-
[10 13 16 19]


In [17]:
print(np.cos(np.pi))   #calc cos of pi
print(np.sqrt(4))   #calc sqrt
print(np.log(6))    #calc the natural logrythim 
print(np.exp(4))    #calc the exponetial

-1.0
2.0
1.791759469228055
54.598150033144236


In [18]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix[0][2])   #display the array by index 0, or row 1, element 3 of that row

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


In [19]:
vec = np.array([4 , 7, 8, 9, 10, 6, 1])
print(vec[vec>6])
print('-')

vec[vec>6]
print(vec)
print('-')

vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2   #replace everything in the array greater than 6 with a 2
print(vec1)

[ 7  8  9 10]
-
[ 4  7  8  9 10  6  1]
-
[4 2 2 2 2 6 1]


In [20]:
loaded_array = np.load('matrix.npy')   #matrix.npy is a data file containing the array matrix

FileNotFoundError: [Errno 2] No such file or directory: 'matrix.npy'

In [21]:
series1 = pd.DataFrame({'column0':[1,2,3],'co1umn1':[5,6,7]})
series2 = pd.DataFrame({'co1umn1':[9,10,11]})
series3 = pd.DataFrame({'column3':[13,14,15]})

dfConcat = pd.concat([series1,series2,series3],axis=0)
print(series1)
print('-')
print(series2)
print('-')
print(series3)
print('-')
print(dfConcat)
print('-')
dfConcat = pd.concat([series1,series2,series3],axis=1)
print(dfConcat)

   column0  co1umn1
0        1        5
1        2        6
2        3        7
-
   co1umn1
0        9
1       10
2       11
-
   column3
0       13
1       14
2       15
-
   column0  co1umn1  column3
0      1.0      5.0      NaN
1      2.0      6.0      NaN
2      3.0      7.0      NaN
0      NaN      9.0      NaN
1      NaN     10.0      NaN
2      NaN     11.0      NaN
0      NaN      NaN     13.0
1      NaN      NaN     14.0
2      NaN      NaN     15.0
-
   column0  co1umn1  co1umn1  column3
0        1        5        9       13
1        2        6       10       14
2        3        7       11       15


In [22]:
df3 = pd.DataFrame({'Yo Boy':[1,2,3],'Yo Chicka':[5,6,7]})
print(df3)

print('-')

df3.reset_index()   #reset the index of df3, wtf is this shit

print(df3)

   Yo Boy  Yo Chicka
0       1          5
1       2          6
2       3          7
-
   Yo Boy  Yo Chicka
0       1          5
1       2          6
2       3          7


In [23]:
df4 = pd.DataFrame({'Name':['Bob','Jenny','Joe','Karen'], 'Age':[5,6,7,9], 'Gender':['M','F','M','F']})
print(df4)
print('-')

df5 = df4.drop('Age', axis = 1)   #drop column and write into new variable
print(df5)
print('-')

print(df4.loc[2])   #print row at index 2
print('-')

print(df4['Age'])   #print the age column
print('-')

    Name  Age Gender
0    Bob    5      M
1  Jenny    6      F
2    Joe    7      M
3  Karen    9      F
-
    Name Gender
0    Bob      M
1  Jenny      F
2    Joe      M
3  Karen      F
-
Name      Joe
Age         7
Gender      M
Name: 2, dtype: object
-
0    5
1    6
2    7
3    9
Name: Age, dtype: int64
-


In [24]:
print(df4)
print('-')

df6 = pd.DataFrame({'Age':[5,6,7,8],'Yo Chicka':[5,6,7,8]})
print(df6)
print('-')

print(pd.merge(df4,df6,how='left',on='Age'))   #show union for variable in on, notice in index 3 the variable is different between the data sets, using the left command means that the data in the first array will be used
print('-')
print(pd.merge(df4,df6,how='right',on='Age'))  #show union for variable in on, notice in index 3 the variable is different between the data sets, using the right command means that the data in the second array will be used
print('-')
print(pd.merge(df4,df6,how='outer',on='Age'))  #show union values
print('-')
print(pd.merge(df4,df6,how='inner',on='Age'))  #show intersetion values
print('-')

    Name  Age Gender
0    Bob    5      M
1  Jenny    6      F
2    Joe    7      M
3  Karen    9      F
-
   Age  Yo Chicka
0    5          5
1    6          6
2    7          7
3    8          8
-
    Name  Age Gender  Yo Chicka
0    Bob    5      M        5.0
1  Jenny    6      F        6.0
2    Joe    7      M        7.0
3  Karen    9      F        NaN
-
    Name  Age Gender  Yo Chicka
0    Bob    5      M          5
1  Jenny    6      F          6
2    Joe    7      M          7
3    NaN    8    NaN          8
-
    Name  Age Gender  Yo Chicka
0    Bob    5      M        5.0
1  Jenny    6      F        6.0
2    Joe    7      M        7.0
3  Karen    9      F        NaN
4    NaN    8    NaN        8.0
-
    Name  Age Gender  Yo Chicka
0    Bob    5      M          5
1  Jenny    6      F          6
2    Joe    7      M          7
-


In [25]:
df7 = pd.DataFrame({'Product':[1,3,3,4],'Age':[5,6,7,8],'Price':[9,10,11,12]})
print(df7['Product'].diff())
print('-')
print(df7['Product'].unique())
print('-')
print(df7['Age'].mean())   #show the average age
print('-')
print(df7.drop('Price', axis = 1))
print('-')
print(df7)
print('-')

0    NaN
1    2.0
2    0.0
3    1.0
Name: Product, dtype: float64
-
[1 3 4]
-
6.5
-
   Product  Age
0        1    5
1        3    6
2        3    7
3        4    8
-
   Product  Age  Price
0        1    5      9
1        3    6     10
2        3    7     11
3        4    8     12
-


In [30]:
variable = ['learning', "Python", 'is fun?', True]
print(variable)
print('-')
variable.append('hello')
print(variable)

['learning', 'Python', 'is fun?', True]
-
['learning', 'Python', 'is fun?', True, 'hello']


In [33]:
variable.remove("Python")
print(variable)

['learning', 'is fun?', True, 'hello']


In [52]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)
print('-')

#harder way todo whats above
list3 = list1 + list2
print(list3)

[1, 2, 3, 4, 5, 6]
-
[1, 2, 3, 4, 5, 6]


In [45]:
list3 = [2.0001, 3.908, 4.56]
sum(list3)

10.4681

In [46]:
list4 = [9, 7, 8, 1, 5]
list4.sort(reverse = True)
list4

[9, 8, 7, 5, 1]

In [70]:
#used to all 3 elements of 3 lists
def sum_3(a, b, c):
        d = a + b + c
        s = sum(d)
        return s

In [71]:
f = lambda x,y,z: x*y/z*z
f(1, 5, 78)

5.0

In [72]:
squares = [x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [73]:
set = [i for i in range(1,101) if i%2 == 0] 
print(set)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [74]:
set = [i for i in range(1,100) if i%2 == 0] 
print(set)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [75]:
set = [i for i in range(1,101) if i%3 == 0] 
print(set)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [76]:
set = [i for i in range(0,101) if i%4 == 0] 
print(set)

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100]


In [77]:
# print the length of each word in the sentence
sentence = 'great learning is a great platform to learn about data science as it has great faculty and content.'
count = [len(i) for i in sentence.split()]
print(count)

[5, 8, 2, 1, 5, 8, 2, 5, 5, 4, 7, 2, 2, 3, 5, 7, 3, 8]


In [78]:
np.identity(2)  #creates a 2d identity matrix

array([[1., 0.],
       [0., 1.]])

In [79]:
np.ones(2)   #creates a 2 item 1d matrix full of ones

array([1., 1.])

In [82]:
np.identity(2*2)   #creates an 2d identity matrix of size 2*2=4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
np.ones(2*2)   #creates a 4 items 1d matrix of ones or of size 2*2=$

array([1., 1., 1., 1.])

In [84]:
np.arange(start = 9, stop = 0, step = -1).reshape(3,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [91]:
#come back to the cock sucker q4







#pay attention here fucker






#look asshole





#ok that was fun back to work


d1 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(d1)
print('-')

d1 * 1
print(d1)
print('-')

add = add(d1,1)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
-
[[9 8 7]
 [6 5 4]
 [3 2 1]]
-


NameError: name 'add' is not defined

In [101]:
#print the average of all matrixes in the array
n6 = np.matrix([[ 1, 4, 9, 121, 144, 169], [ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]]).mean()
print(n6)

131.66666666666666


In [102]:
#dot product here, im not sure wtf a dot product is




#research this one some more 



#your high now so lookinto this later, pay attention fuckers



n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
#help(np.dot)
np.dot(n1, n2)

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [114]:
np.arange(6)[2:7]    #this is nifty create an array of all numbers between 2 and 7 but stoping before 6

array([2, 3, 4, 5])

In [117]:
np.arange(20)[0::9]

array([ 0,  9, 18])

In [128]:
#which command reverses the array 
p = np.arange(20)
print(p)
print('-')

p[:-1]
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
-
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [124]:
np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])[::-1]

matrix([[9, 4, 8],
        [1, 5, 4],
        [1, 4, 9]])

In [125]:
np.arange(start = 9, stop = 0, step = -1).reshape(3,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [136]:
#run these seperate but together from here down to (ABC)

import numpy as np

In [137]:
demo_array = np.arange(0,10)

In [138]:
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
demo_array <3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [140]:
demo_array[demo_array <6]

array([0, 1, 2, 3, 4, 5])

In [142]:
np.max(demo_array)

#(ABC) this is the end of this block, its nifty seeing what happens when you run them indepedenant of each other

9

In [143]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [144]:
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [145]:
test_array = [10, 11.5, 12, 13.5, 14,15]

In [146]:
test_array[2:3]

[12]

In [147]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

In [149]:
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [150]:
score = [10, 15, 20, 25]

In [151]:
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [155]:
newcolumn =  ["A", "B", "C", "D", "E"]

newcolumn = ["A", "B", "C", "D", "E"]

In [176]:
#create array 'dataframe' with index names and then add row names as well then append a new column into the array
dataframe = pd.DataFrame([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]], columns=['word1','word2','word3','word4','word5'])
dataframe.index = rows = ['l','m','n','o','p']


newcolumn = ["A", "B", "C", "D", "E"]

newcolumn = ["A", "B", "C", "D", "E"]

dataframe['Alphabets'] = newcolumn


print(dataframe)

   word1  word2  word3  word4  word5 Alphabets
l      1      2      3      4      5         A
m      1      2      3      4      5         B
n      1      2      3      4      5         C
o      1      2      3      4      5         D
p      1      2      3      4      5         E


In [178]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [179]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [180]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [185]:
#Concatonate two series together 
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [195]:
football = [24, 235, 34, 456, 65, 67]
#np.array{football}
#np.array[‘football’]
np.array(football)
#np.array[football]
print(football)
type(football)

[24, 235, 34, 456, 65, 67]


list