In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Wine.csv')

In [3]:
df = data.copy()

In [4]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [8]:
df.describe().T

count        mean         std     min       25%  \
alcohol                       178.0   13.000618    0.811827   11.03   12.3625   
malic_acid                    178.0    2.336348    1.117146    0.74    1.6025   
ash                           178.0    2.366517    0.274344    1.36    2.2100   
alcalinity_of_ash             178.0   19.494944    3.339564   10.60   17.2000   
magnesium                     178.0   99.741573   14.282484   70.00   88.0000   
total_phenols                 178.0    2.295112    0.625851    0.98    1.7425   
flavanoids                    178.0    2.029270    0.998859    0.34    1.2050   
nonflavanoid_phenols          178.0    0.361854    0.124453    0.13    0.2700   
proanthocyanins               178.0    1.590899    0.572359    0.41    1.2500   
color_intensity               178.0    5.058090    2.318286    1.28    3.2200   
hue                           178.0    0.957449    0.228572    0.48    0.7825   
od280/od315_of_diluted_wines  178.0    2.611685    0.709990    1.27    1.9375   
proline                       178.0  746.893258  314.907474  278.00  500.5000   

                                  50%       75%      max  
alcohol                        13.050   13.6775    14.83  
malic_acid                      1.865    3.0825     5.80  
ash                             2.360    2.5575     3.23  
alcalinity_of_ash              19.500   21.5000    30.00  
magnesium                      98.000  107.0000   162.00  
total_phenols                   2.355    2.8000     3.88  
flavanoids                      2.135    2.8750     5.08  
nonflavanoid_phenols            0.340    0.4375     0.66  
proanthocyanins                 1.555    1.9500     3.58  
color_intensity                 4.690    6.2000    13.00  
hue                             0.965    1.1200     1.71  
od280/od315_of_diluted_wines    2.780    3.1700     4.00  
proline                       673.500  985.0000  1680.00

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [11]:
df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [19]:
dm = np.arange(10,21)

In [20]:
subDm = dm[0:7]

In [21]:
subDm

array([10, 11, 12, 13, 14, 15, 16])

In [22]:
subDm[:] = 101

In [23]:
subDm

array([101, 101, 101, 101, 101, 101, 101])

In [24]:
demo_matrix = np.array([[13,35,74,48], [23,37,37,38],[73,39,93,39]])

In [26]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [25]:
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [27]:
test_array = np.array([1,2,3,4,5,6,7,8,9,10]) 

In [28]:
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
bool = test_array > 5
bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [32]:
array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29])
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [34]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [42]:
#df['alcohol', 'mallc_acid', 'ash']
df[['alcohol', 'ash', 'magnesium']]

alcohol   ash  magnesium
0      14.23  2.43      127.0
1      13.20  2.14      100.0
2      13.16  2.67      101.0
3      14.37  2.50      113.0
4      13.24  2.87      118.0
..       ...   ...        ...
173    13.71  2.45       95.0
174    13.40  2.48      102.0
175    13.27  2.26      120.0
176    13.17  2.37      120.0
177    14.13  2.74       96.0

[178 rows x 3 columns]

In [45]:
# create array, name the columns and index
num = np.array([[1,2,53,34], [15,12,43,78],[24,35,83,99],[28,62,73,22]])
q8 = pd.DataFrame(num, columns = ['W','X','Y','Z'], index = ['A','B','C','D'])
q8

W   X   Y   Z
A   1   2  53  34
B  15  12  43  78
C  24  35  83  99
D  28  62  73  22

In [46]:
q8.loc[['A', 'B'], ['Y', 'Z']]

Y   Z
A  53  34
B  43  78

In [47]:
df.loc[[2,3],['magnesium', 'total_phenols']]


magnesium  total_phenols
2      101.0           2.80
3      113.0           3.85

In [48]:
df['alcalinity_of_ash'].mean()

19.49494382022472

In [49]:
df['malic_acid']

0      1.71
1      1.78
2      2.36
3      1.95
4      2.59
       ... 
173    5.65
174    3.91
175    4.28
176    2.59
177    4.10
Name: malic_acid, Length: 178, dtype: float64

In [50]:
def edit_col(col):
    col = col*2 + 10
    return col

df.malic_acid.apply(edit_col)

0      13.42
1      13.56
2      14.72
3      13.90
4      15.18
       ...  
173    21.30
174    17.82
175    18.56
176    15.18
177    18.20
Name: malic_acid, Length: 178, dtype: float64

In [53]:
df.sort_values(by = 'total_phenols')

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
146    13.88        5.04  2.23               20.0       80.0           0.98   
70     12.29        1.61  2.21               20.4      103.0           1.10   
132    12.81        2.31  2.40               24.0       98.0           1.15   
170    12.20        3.03  2.32               19.0       96.0           1.25   
165    13.73        4.36  2.26               22.5       88.0           1.28   
..       ...         ...   ...                ...        ...            ...   
58     13.72        1.43  2.50               16.7      108.0           3.40   
63     12.37        1.13  2.16               19.0       87.0           3.50   
98     12.37        1.07  2.10               18.5       88.0           3.52   
3      14.37        1.95  2.50               16.8      113.0           3.85   
52     13.82        1.75  2.42               14.0      111.0           3.88   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity  \
146        0.34                  0.40             0.68             4.90   
70         1.02                  0.37             1.46             3.05   
132        1.09                  0.27             0.83             5.70   
170        0.49                  0.40             0.73             5.50   
165        0.47                  0.52             1.15             6.62   
..          ...                   ...              ...              ...   
58         3.67                  0.19             2.04             6.80   
63         3.10                  0.19             1.87             4.45   
98         3.75                  0.24             1.95             4.50   
3          3.49                  0.24             2.18             7.80   
52         3.74                  0.32             1.87             7.05   

       hue  od280/od315_of_diluted_wines  proline  
146  0.580                          1.33    415.0  
70   0.906                          1.82    870.0  
132  0.660                          1.36    560.0  
170  0.660                          1.83    510.0  
165  0.780                          1.75    520.0  
..     ...                           ...      ...  
58   0.890                          2.87   1285.0  
63   1.220                          2.87    420.0  
98   1.040                          2.77    660.0  
3    0.860                          3.45   1480.0  
52   1.010                          3.26   1190.0  

[178 rows x 13 columns]